@url = localhost:3000

### valid admin register
POST http://{{url}}/auth/admins/register
Content-Type: application/json

{
  "username": "usernameTest",
  "email": "username@prueba.com",
  "password": "123"
}

### invalid admin register: register without username
POST http://{{url}}/auth/admins/register
Content-Type: application/json

{
  "username": "",
  "email": "username2@prueba.com",
  "password": "123"
}

### invalid admin register: register without email
POST http://{{url}}/auth/admins/register
Content-Type: application/json

{
  "username": "username2Test",
  "email": "",
  "password": "123"
}

### invalid admin register: register without password
POST http://{{url}}/auth/admins/register
Content-Type: application/json

{
  "username": "username2Test",
  "email": "username2@prueba.com",
  "password": ""
}

### invalid admin register: register with invalid email
POST http://{{url}}/auth/admins/register
Content-Type: application/json

{
  "username": "username2Test",
  "email": "username2prueba.com",
  "password": "123"
}



### valid admin login
POST http://{{url}}/auth/admins/login
Content-Type: application/json

{
  "emailOrUsername": "username@prueba.com",
  "password": "123"
}

### invalid admin login: admin login without email
POST http://{{url}}/auth/admins/login
Content-Type: application/json

{
"emailOrUsername": "",
"password": "123"
}

### invalid admin login: admin login without password
POST http://{{url}}/auth/admins/login
Content-Type: application/json

{
"email": "username@prueba.com",
"password": ""
}

### invalid admin login: admin login with invalid email
POST http://{{url}}/auth/admins/login
Content-Type: application/json

{
  "emailOrUsername": "invalid@prueba.com",
  "password": "123"
}

### admin_login_with_invalid_password
POST http://{{url}}/auth/admins/login
Content-Type: application/json

{
  "emailOrUsername": "username@prueba.com",
  "password": "12345"
}

### admin_login_with_invalid_password
POST http://localhost:3000/auth/admins/login
Content-Type: application/json

{
  "emailOrUsername": "usernameTest",
  "password": "12345"
}

