### admin_register_valid

POST http://localhost:3000/auth/admins/register
Content-Type: application/json

{
  "username": "usernameTest",
  "email": "username@prueba.com",
  "password": "123456"
}

### admin_register_without_username
POST http://localhost:3000/auth/admins/register
Content-Type: application/json

{
  "username": "",
  "email": "username@prueba.com",
  "password": "123456"
}

### admin_register_invalid_email
POST http://localhost:3000/auth/admins/register
Content-Type: application/json

{
  "username": "username2Test",
  "email": "username2prueba.com",
  "password": "12345"
}

### admin_login_valid
POST http://localhost:3000/auth/admins/login
Content-Type: application/json

{
  "emailOrUsername": "username@prueba.com",
  "password": "123456"
}
### admin_login_without_email
POST http://localhost:3000/auth/admins/login
Content-Type: application/json

{
"emailOrUsername": "",
"password": "123456"
}

### invalid_admin_login
POST http://localhost:3000/auth/admins/login
Content-Type: application/json

{
  "emailOrUsername": "invalid@prueba.com",
  "password": "123456"
}

### admin_login_with_invalid_password
POST http://localhost:3000/auth/admins/login
Content-Type: application/json

{
  "emailOrUsername": "username@prueba.com",
  "password": "12345"
}

### admin_login_with_invalid_password
POST http://localhost:3000/auth/admins/login
Content-Type: application/json

{
  "emailOrUsername": "usernameTest",
  "password": "12345"
}

