@url = localhost:3000
@validToken =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWRtaW4iLCJlbWFpbCI6InVzZXJuYW1lQHBydWViYS5jb20iLCJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdCIsImlhdCI6MTcyNzEyNDcwNywiZXhwIjoxNzU4NjYwNzA3fQ.JKHPWPO3S_K272irRnqtaVebaxhhwjNsjJjtI6TShYA

### admin list users with authorization
GET http://{{url}}/admins/users
Authorization: {{validToken}}
Content-Type: application/json

### admin get user by id with authorization
GET http://{{url}}/admins/users/1
Authorization: validToken
Content-Type: application/json

