@url = localhost:3000
@validToken =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWRtaW4iLCJlbWFpbCI6InVzZXJuYW1lQHBydWViYS5jb20iLCJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdCIsImlhdCI6MTcyNzIwMTIyNCwiZXhwIjoxNzU4NzM3MjI0fQ.dbEBv5SP0WMG4pxHDSwWU638_86fp9JN_DaIFNPX4c8
@username = luis4
### admin list users with authorization
GET http://{{url}}/admins/users
Authorization: {{validToken}}
Content-Type: application/json

### admin get user by username with authorization
GET http://{{url}}/admins/users/{{username}}
Authorization: {{validToken}}
Content-Type: application/json

