@url = localhost:3000
@validToken =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWRtaW4iLCJlbWFpbCI6InVzZXJuYW1lQHBydWViYS5jb20iLCJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdCIsImlhdCI6MTcyNzEyODYwNCwiZXhwIjoxNzU4NjY0NjA0fQ.PxVK3rzmJyUiTZdIyaJu8N2oi55ecKeXi_IDMTjpEEo

### admin list users with authorization
GET http://{{url}}/admins/users
Authorization: {{validToken}}
Content-Type: application/json

### admin get user by username with authorization
GET http://{{url}}/admins/users/martin
Authorization: {{validToken}}
Content-Type: application/json

