@url = http://localhost:3000
@invalidToken = Bearer ey.invalidtoken.signature
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsInVzZXJJZCI6MSwiZW1haWwiOiJsdWlzQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoibHVpcyIsInBob25lTnVtYmVyIjoiKzU0MTEyNzc2MjY5MyIsInZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzMyMzg4ODUxLCJleHAiOjE3NjM5MjQ4NTF9.NQps1sunaF-IHKA1J7zDEB1VadQMrh56lhlZJAsUq6M


### get all users UNAUTHORIZED
curl -X GET {{url}}/users


### get all users UNAUTHORIZED
curl -X GET {{url}}/users \
    -H 'Authorization: {{invalidToken}}'


### get all users AUTHORIZED
curl -X GET {{url}}/users \
    -H 'Authorization: {{token}}'

### get user AUTHORIZED
curl -X GET {{url}}/users/luis4 \
    -H 'Authorization: {{token}}'


### get all interests
curl -X GET {{url}}/users/interests/all \
    -H 'Authorization: {{token}}'


### get user interests
curl -X GET {{url}}/users/interests \
    -H 'Authorization: {{token}}'
