@url = http://localhost:3000

### forgot password
curl -X POST {{url}}/auth/forgot-password \
    -H 'Content-Type: application/json' \
    -d '{
        "email": "escalanteluis2001@gmail.com"
    }'
