@url = https://twitsnap-users.up.railway.app


### login
curl -X POST {{url}}/auth/login \
    -H 'Content-Type: application/json' \
    -d '{
        "emailOrUsername": "luis@gmail.com",
        "password": "luis123"
    }'


### register
curl -X POST {{url}}/auth/register \
    -H 'Content-Type: application/json' \
    -d '{
        "email": "luis@gmail.com",
        "username": "luis",
        "password": "luis123",
        "name": "name test",
        "lastname": "lastname test",
        "birthdate": "1990-01-01"
    }'