@url = http://localhost:3000
@invalidToken = Bearer ey.invalidtoken.signature
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsInVzZXJJZCI6MSwiZW1haWwiOiJsdWlzNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Imx1aXM0IiwiaWF0IjoxNzI4MzM2NTMzLCJleHAiOjE3NTk4NzI1MzN9.rDRP_gLQ-MdCJwj9vyInwsVNVMmY4XJcYQSr_pepQ2w
@username = luis4

### get all users UNAUTHORIZED
curl -X GET {{url}}/user


### get all users UNAUTHORIZED
curl -X GET {{url}}/user \
    -H 'Authorization: {{invalidToken}}'  


### get all users UNAUTHORIZED
curl -X GET {{url}}/user \
    -H 'Authorization: {{token}}'


### get twits from a useranme
GET {{url}}/users/{{username}}
Authorization: {{token}}
Content-Type: application/json
