@url = https://twitsnap-users.up.railway.app

# get all users
curl -X GET {{url}}/user

### register
curl -X POST {{url}}/user \
    -H 'Content-Type: application/json' \
    -d '{
        "email": "maxi@fi.uba.ar",
        "password": "123456",
        "username": "maxi",
        "name": "name test"
    }'


### auth
curl -X GET {{url}}/auth


### login
curl -X POST {{url}}/auth/login \
    -H 'Content-Type: application/json' \
    -d '{
        "email": "email",
        "password": "123456"
    }'


### register
curl -X POST {{url}}/auth/register \
    -H 'Content-Type: application/json' \
    -d '{
        "email": "email",
        "password": "123456",
        "name": "name test"
    }'