### admin_register_valid

POST http://localhost:3000/auth/admin/register
Content-Type: application/json

{
  "username": "usernameTest",
  "email": "username@prueba.com",
  "password": "123456"
}

### admin_register_without_username
POST http://localhost:3000/auth/admin/register
Content-Type: application/json

{
  "username": "",
  "email": "username@prueba.com",
  "password": "123456"
}

### admin_register_invalid_email
POST http://localhost:3000/auth/admin/register
Content-Type: application/json

{
  "username": "username2Test",
  "email": "username2prueba.com",
  "password": "12345"
}

### admin_login_valid
POST http://localhost:3000/auth/admin/login
Content-Type: application/json

{
  "email": "username@prueba.com",
  "password": "123456"
}
### admin_login_without_email
POST http://localhost:3000/auth/admin/login
Content-Type: application/json

{
"email": "",
"password": "123456"
}

### invalid_admin_login
POST http://localhost:3000/auth/admin/login
Content-Type: application/json

{
  "email": "invalid@prueba.com",
  "password": "123456"
}

### admin_login_with_invalid_password
POST http://localhost:3000/auth/admin/login
Content-Type: application/json

{
  "email": "username@prueba.com",
  "password": "12345"
}

### admin_list_users
GET http://localhost:3000/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWRtaW4iLCJlbWFpbCI6InVzZXJuYW1lQHBydWViYS5jb20iLCJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdCIsImlhdCI6MTcyNzA1MjYzMiwiZXhwIjoxNzU4NTg4NjMyfQ.nC9wrbHI7yWrX4jrLcrlh6ymDdLc8NenfRhpsb0e6pA
Content-Type: application/json

### admin_get_user_by_id
GET http://localhost:3000/admin/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWRtaW4iLCJlbWFpbCI6InVzZXJuYW1lQHBydWViYS5jb20iLCJ1c2VybmFtZSI6InVzZXJuYW1lVGVzdCIsImlhdCI6MTcyNzA1MjYzMiwiZXhwIjoxNzU4NTg4NjMyfQ.nC9wrbHI7yWrX4jrLcrlh6ymDdLc8NenfRhpsb0e6pA
Content-Type: application/json

